#!/bin/bash

#prior 
#awk -F'\t' 'BEGIN {OFS="\t"} { $1 = substr($1, 4); print }'  tair10_control_neg_NoTF_NoTSS_TES.tsv > tair10_control_neg_NoTF_NoTSS_TES_nochr.tsv

###
# Formate to bed format the file generated by gene2proteo to effectuate mapping betweens coords and AA sequence
awk -F'\t' '{print $1,$2,$3,$5,$6,$4,$8,$12}' OFS=$'\t' dm6.ncbiRefSeq_idprot.gtf.gz_AAseq.txt > to_ovlp_map_aa_seq_file_dm6.bed
awk -F'\t' '{print $1,$2,$3,$5,$6,$4,$8,$12}' OFS=$'\t' Arabidopsis_thaliana.TAIR10.44.gtf.gz_AAseq.txt > to_ovlp_map_aa_seq_file_tair10.bed

bedtools intersect -s -a /home/mouren/Data/final_files_tokeep/other_species/dm6_EE.bed -b to_ovlp_map_aa_seq_file_dm6.bed -wa -wb > tmp
#remove duplicates rows
awk '
BEGIN {
    FS = OFS = "\t"
}
{
    key = ""
    for (i = 1; i <= NF; i++) {
        if (i != 10 && i != 11) {
            key = key $i OFS
        }
    }
    if (!seen[key]++) {
        print
    }
}
' tmp > /home/mouren/Data/final_files_tokeep/aa_sequences/results_tool/res_ovlp_ee_aa_seq_dm6.tsv


bedtools intersect -s -a /home/mouren/Data/final_files_tokeep/other_species/control/dm6_control_neg_NoTF_NoTSS_TES.tsv -b to_ovlp_map_aa_seq_file_dm6.bed -wa -wb > tmp
#remove duplicates rows
awk '
BEGIN {
    FS = OFS = "\t"
}
{
    key = ""
    for (i = 1; i <= NF; i++) {
        if (i != 10 && i != 11) {
            key = key $i OFS
        }
    }
    if (!seen[key]++) {
        print
    }
}
' tmp > /home/mouren/Data/final_files_tokeep/aa_sequences/results_tool/res_ovlp_neg_aa_seq_dm6.tsv

bedtools intersect -s -a /home/mouren/Data/final_files_tokeep/other_species/tair10_EE_nochr.bed -b to_ovlp_map_aa_seq_file_tair10.bed -wa -wb > tmp
#remove duplicates rows
awk '
BEGIN {
    FS = OFS = "\t"
}
{
    key = ""
    for (i = 1; i <= NF; i++) {
        if (i != 10 && i != 11) {
            key = key $i OFS
        }
    }
    if (!seen[key]++) {
        print
    }
}
' tmp > /home/mouren/Data/final_files_tokeep/aa_sequences/results_tool/res_ovlp_ee_aa_seq_tair10.tsv

bedtools intersect -s -a /home/mouren/Data/final_files_tokeep/other_species/control/tair10_control_neg_NoTF_NoTSS_TES_nochr.tsv -b to_ovlp_map_aa_seq_file_tair10.bed -wa -wb > tmp
#remove duplicates rows
awk '
BEGIN {
    FS = OFS = "\t"
}
{
    key = ""
    for (i = 1; i <= NF; i++) {
        if (i != 10 && i != 11) {
            key = key $i OFS
        }
    }
    if (!seen[key]++) {
        print
    }
}
' tmp > /home/mouren/Data/final_files_tokeep/aa_sequences/results_tool/res_ovlp_neg_aa_seq_tair10.tsv

rm tmp